FROM ghcr.io/puppeteer/puppeteer:19.7.2

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci
COPY . .
RUN ls -la /usr/bin/*chrome* /usr/bin/*chromium* \
    && echo "Chromium path: $(which chromium-browser)"
CMD [ "node", "server.js" ]